### ISSUE TITLE
👋  Incorrect url in repo About Me section 

### ISSUE THREAD

**Issue by mattlovestech** [trevv16/rental-property-calc-ts#1]
Hi @trevv16 great work on `rental-property-calc-ts` 🥳 . I was trying to test out a live version using the url provided in the screen shot above which took me to [caption-search.netlify.app/](https://caption-search.netlify.app/) but, I think you intended to point people to https://rental-calc.netlify.app/.

<img width="322" alt="Screen Shot 2022-11-12 at 10 13 45 PM" src="https://user-images.githubusercontent.com/45296246/201503882-ebcbb34c-0ce2-4b8d-8f56-41c63c3c99b2.png">

**Comment by trevv16** [comment]
Hi @mattlovestech sorry I am just seeing this. Thank you for this I have updated the url.

**Comment by mattlovestech** [comment]
No problem @trevv16 !
